[package]
edition = "2021"
name    = "hopr-strategy-integration-tests"
publish = false
version = "0.1.0"

[dependencies]

anyhow = { workspace = true }
futures = { workspace = true }
hopr-api = { workspace = true, features = ["node", "serde"] }
hopr-strategy = { workspace = true, features = [
  "runtime-tokio",
  "strategy-auto-funding",
  "strategy-auto-redeeming",
  "strategy-channel-lifecycle",
  "strategy-closure-finalizer",
  "testing",
] }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }

[dev-dependencies]

bytesize = { workspace = true }
test-log = { workspace = true, features = ["trace"] }
