//! Persistent encrypted store for Exit-side
//! [`PixEvent::PrivateKeyRecovered`](hopr_api::node::PixEvent::PrivateKeyRecovered) events.
//!
//! # Encryption scheme
//!
//! ```text
//! Config password  ──→  scrypt(password, per-db-salt)  ──→  256-bit key
//!                                                                 │
//!                                              ┌──────────────────┤
//!                                              │                  │
//!                 Per-entry random nonce (12) ─┤         ChaCha20Poly1305
//!                                              │                  │
//!                     AAD = entry key (14) ────┤                  │
//!                                              │                  │
//!                                  Plaintext   │                  │
//!                                  (32 bytes)  ──→  encrypt      │
//!                                                                 │
//!                                  Stored = nonce (12) ||         │
//!                                           ciphertext (48)    ←──┘
//! ```
//!
//! **Key derivation.**  When the store is opened, the config-supplied password
//! is fed through scrypt (RFC 7914) with recommended parameters (log₂_N = 17,
//! r = 8, p = 1).  A **random 16-byte salt** is generated once per database on
//! first open and persisted in a dedicated redb metadata table, so reopening
//! the same database uses the same salt.  This prevents pre-computation attacks
//! across databases.
//!
//! **Password check.**  A fixed known plaintext is encrypted under the derived key
//! and stored alongside the salt on first open.  Every later open decrypts it and
//! refuses to proceed when it does not match, so a rotated or mistyped password
//! is reported instead of yielding a store whose entries all fail to decrypt.
//!
//! **Per-entry nonce.**  Each encrypted entry begins with a fresh random 12-byte
//! nonce generated by `thread_rng`.  Because every entry gets its own random
//! nonce, there is no risk of nonce reuse even when the same `PixAddressId` is
//! re-encrypted after deletion.
//!
//! **Authenticated encryption.**  Each 32-byte private key is encrypted with
//! ChaCha20Poly1305 (RFC 8439).  The 16-byte authentication tag is appended,
//! producing a 48-byte ciphertext.  Combined with the 12-byte nonce, each stored
//! value is 60 bytes.  Any tampering with the stored ciphertext (bit flips,
//! truncation, etc.) is detected on decryption; the corrupt entry is skipped
//! during iteration and the skip is logged.
//!
//! **Entry binding.**  The encoded database key is passed as ChaCha20Poly1305
//! associated data, so each ciphertext authenticates the `PixAddressId` it is
//! filed under.  A value copied or swapped to a different key fails to decrypt
//! rather than yielding another entry's secret — otherwise a sweep would be
//! attempted with a private key that does not belong to the deposit address.
//! The password verifier is bound to an all-zero associated-data value, which
//! `encode_key` cannot produce, so it cannot be exchanged with a real entry.
//!
//! **Key layout.**  The database key is the `PixAddressId` encoded as
//! `HoprPseudonym::SIZE` bytes of pseudonym followed by a 4-byte big-endian SSA
//! index.  The key is deterministic (no randomness), so `contains()` and
//! `insert()` work naturally.
//!
//! ## Threat model
//!
//! This protects against an attacker who obtains read-only access to the
//! database file (e.g. via a filesystem backup, exfiltration, or stolen disk).
//! Without the config password they cannot derive the encryption key, and
//! without the key they cannot decrypt any entry.
//!
//! An attacker who can *write* to the file cannot forge an entry or move one
//! between `PixAddressId`s undetected, because every ciphertext is bound to its
//! key (see **Entry binding**).  They can still delete entries or the whole
//! file, which loses the pending sweep for those deposits.
//!
//! It does **not** protect against:
//! - An attacker who also has the config (the password comes from the same config file).
//! - An attacker who can execute code as the node process (they can read the derived key from process memory).
//! - An attacker who can read the node's process environment.  The password is passed via an environment variable,
//!   which is readable through `/proc/<pid>/environ` by the same user and by root, is visible to anything that inspects
//!   the process table, and is inherited by every child process the node spawns.  Keeping the password out of the
//!   config file narrows the on-disk exposure; it does not eliminate exposure to a local attacker.
//! - Side-channel or fault-analysis attacks.
//!
//! ## Recovery on restart
//!
//! On node restart every stored entry is iterated and its sweep re-attempted,
//! providing crash recovery.  An entry is removed only once funds have actually
//! moved, so a deposit that has not landed yet stays pending for a later start
//! rather than being dropped.
//!
//! The store is only opened in the Exit role (when
//! [`crate::pix::strategy::PixStrategyConfig::pix_recovery_db_path`] and
//! [`crate::pix::strategy::PixStrategyConfig::pix_recovery_password_env`] are both set).

use std::{num::NonZeroU32, path::Path, sync::Arc};

use chacha20poly1305::{
    ChaCha20Poly1305, Key, KeyInit, Nonce,
    aead::{Aead, Payload},
};
use hopr_api::{
    chain::PixDepositSecret,
    node::PixAddressId,
    types::{crypto_random::random_bytes, internal::prelude::HoprPseudonym, primitive::traits::BytesRepresentable},
};
use redb::{Database, ReadableDatabase, ReadableTable, TableDefinition};
use scrypt::{Params as ScryptParams, scrypt};

// Key = pseudonym (10 bytes) + ssa_index (4 bytes)
const KEY_SIZE: usize = HoprPseudonym::SIZE + 4;

// Value = nonce (12 bytes) + ciphertext (32 + 16 tag)
const NONCE_SIZE: usize = 12;
const VALUE_SIZE: usize = NONCE_SIZE + 32 + 16;

const PIX_RECOVERED_KEYS: TableDefinition<[u8; KEY_SIZE], [u8; VALUE_SIZE]> =
    TableDefinition::new("pix_recovered_keys");

/// Per-database scrypt salt, stored in a separate table.
const PIX_KDF_SALT_TABLE: TableDefinition<u8, [u8; 16]> = TableDefinition::new("pix_kdf_salt");

/// Encrypted [`VERIFIER_PLAINTEXT`], used to reject a wrong password at [`PixRecoveryStore::open`].
const PIX_KDF_VERIFIER_TABLE: TableDefinition<u8, [u8; VALUE_SIZE]> = TableDefinition::new("pix_kdf_verifier");

/// Known plaintext encrypted under the derived key so the key can be checked on open.
const VERIFIER_PLAINTEXT: [u8; 32] = *b"hopr-pix-recovery-store-verifier";

/// Associated data binding the verifier record to its own slot.
///
/// All-zero, which [`encode_key`] can never produce: its trailing SSA index comes from a
/// `NonZeroU32`. So the verifier ciphertext can never be relocated into an entry slot, nor an
/// entry ciphertext into the verifier slot.
const VERIFIER_AAD: [u8; KEY_SIZE] = [0u8; KEY_SIZE];

/// Persistent encrypted recovery key store backed by `redb`.
///
/// # Examples
///
/// The Exit-side lifecycle of one recovered key: persist it as soon as the event arrives, sweep
/// it, then drop it once the funds have moved. The insert happens *before* the sweep is
/// attempted, which is what lets an unfinished sweep be replayed from [`Self::iter`] on the next
/// start.
///
/// ```no_run
/// use hopr_api::{chain::PixDepositSecret, node::PixAddressId};
/// use hopr_strategy::pix::recovery_store::PixRecoveryStore;
///
/// # fn main() -> anyhow::Result<()> {
/// let store = PixRecoveryStore::open("/var/lib/hoprd/pix_recovery.db", "correct horse battery")?;
///
/// # let id: PixAddressId = unimplemented!();
/// # let secret: PixDepositSecret = unimplemented!();
/// // A `PrivateKeyRecovered` event arrived: persist before doing anything with it.
/// if store.insert(&id, &secret)? {
///     // ... hand the secret to the pool's `withdraw_deposit` ...
///     // Only once the funds have moved does the entry go.
///     store.remove(&id)?;
/// }
///
/// // On the next start, whatever never made it through the sweep is still here.
/// for (id, secret) in store.iter()? {
///     let _ = (id, secret);
/// }
/// # Ok(())
/// # }
/// ```
#[derive(Clone)]
pub struct PixRecoveryStore {
    db: Arc<Database>,
    encryption_key: [u8; 32],
}

/// Errors from the PIX recovery store.
#[derive(Debug, thiserror::Error)]
pub enum PixRecoveryStoreError {
    #[error("database error: {0}")]
    Database(#[from] redb::Error),
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("encryption error")]
    Encryption,
    #[error("decryption error")]
    Decryption,
    #[error("corrupt key: {0}")]
    CorruptKey(String),
    #[error("the configured password does not match this recovery store")]
    WrongPassword,
}

impl From<redb::DatabaseError> for PixRecoveryStoreError {
    fn from(error: redb::DatabaseError) -> Self {
        Self::Database(error.into())
    }
}

impl From<redb::TransactionError> for PixRecoveryStoreError {
    fn from(error: redb::TransactionError) -> Self {
        Self::Database(error.into())
    }
}

impl From<redb::TableError> for PixRecoveryStoreError {
    fn from(error: redb::TableError) -> Self {
        Self::Database(error.into())
    }
}

impl From<redb::StorageError> for PixRecoveryStoreError {
    fn from(error: redb::StorageError) -> Self {
        Self::Database(error.into())
    }
}

impl From<redb::CommitError> for PixRecoveryStoreError {
    fn from(error: redb::CommitError) -> Self {
        Self::Database(error.into())
    }
}

// ── Key encoding ─────────────────────────────────────────────────────────────
// Key: `HoprPseudonym::SIZE` bytes of pseudonym + 4 bytes big-endian NonZeroU32.
// Every offset is derived from `HoprPseudonym::SIZE` so the layout follows the type.

fn encode_key(id: &PixAddressId) -> [u8; KEY_SIZE] {
    let (pseudonym, ssa_index) = id;
    let pseudonym_bytes: &[u8] = pseudonym.as_ref();
    let ssa_bytes = ssa_index.get().to_be_bytes();
    let mut out = [0u8; KEY_SIZE];
    out[..HoprPseudonym::SIZE].copy_from_slice(pseudonym_bytes);
    out[HoprPseudonym::SIZE..].copy_from_slice(&ssa_bytes);
    out
}

fn decode_key(bytes: &[u8; KEY_SIZE]) -> Result<PixAddressId, PixRecoveryStoreError> {
    let pseudonym = HoprPseudonym::from(
        <[u8; HoprPseudonym::SIZE]>::try_from(&bytes[..HoprPseudonym::SIZE])
            .map_err(|_| PixRecoveryStoreError::CorruptKey("pseudonym slice".into()))?,
    );

    let ssa_index_bytes: [u8; 4] = <[u8; 4]>::try_from(&bytes[HoprPseudonym::SIZE..KEY_SIZE])
        .map_err(|_| PixRecoveryStoreError::CorruptKey("ssa index slice".into()))?;
    let ssa_index = NonZeroU32::new(u32::from_be_bytes(ssa_index_bytes))
        .ok_or_else(|| PixRecoveryStoreError::CorruptKey("zero ssa index".into()))?;

    Ok((pseudonym, ssa_index))
}

fn derive_key(password: &str, salt: &[u8]) -> [u8; 32] {
    let mut key = [0u8; 32];

    scrypt(password.as_bytes(), salt, &ScryptParams::RECOMMENDED, &mut key)
        .expect("scrypt with 32-byte output must succeed");
    key
}

// ── Encryption helpers ───────────────────────────────────────────────────────

/// Encrypt `plaintext`, binding the result to `aad` — the database key the value is filed
/// under. A value moved to a different key no longer authenticates, so relocating a stored
/// ciphertext turns it into a decryption failure instead of another entry's secret.
fn encrypt(
    key: &[u8; 32],
    aad: &[u8; KEY_SIZE],
    plaintext: &[u8; 32],
) -> Result<[u8; VALUE_SIZE], PixRecoveryStoreError> {
    let cipher = ChaCha20Poly1305::new(&Key::from(*key));
    let nonce_bytes = random_bytes::<NONCE_SIZE>();
    let nonce = Nonce::from(nonce_bytes);

    let ciphertext = cipher
        .encrypt(
            &nonce,
            Payload {
                msg: plaintext.as_ref(),
                aad,
            },
        )
        .map_err(|_| PixRecoveryStoreError::Encryption)?;

    // ChaCha20Poly1305 output = plaintext_len + 16-byte tag = 48 bytes
    let mut out = [0u8; VALUE_SIZE];
    out[..NONCE_SIZE].copy_from_slice(&nonce_bytes);
    out[NONCE_SIZE..].copy_from_slice(&ciphertext);
    Ok(out)
}

/// Decrypt `stored`, which must have been encrypted under the same `aad`. `aad` is the
/// database key the value was read from, so a value that has been moved between keys fails
/// here rather than decrypting into the wrong entry's secret.
fn decrypt(key: &[u8; 32], aad: &[u8; KEY_SIZE], stored: &[u8; VALUE_SIZE]) -> Result<[u8; 32], PixRecoveryStoreError> {
    let cipher = ChaCha20Poly1305::new(&Key::from(*key));
    let nonce_arr: [u8; NONCE_SIZE] = stored[..NONCE_SIZE]
        .try_into()
        .map_err(|_| PixRecoveryStoreError::Decryption)?;
    let nonce = Nonce::from(nonce_arr);

    let plaintext = cipher
        .decrypt(
            &nonce,
            Payload {
                msg: &stored[NONCE_SIZE..],
                aad,
            },
        )
        .map_err(|_| PixRecoveryStoreError::Decryption)?;

    Ok(plaintext
        .as_slice()
        .try_into()
        .expect("ChaCha20Poly1305 plaintext is 32 bytes"))
}

impl PixRecoveryStore {
    /// Open (or create) the `redb` database at `path` with encryption key derived from `password`.
    ///
    /// Fails with [`PixRecoveryStoreError::WrongPassword`] when `password` does not match the
    /// one the database was created with. Without that check a rotated or mistyped password
    /// would leave every entry undecryptable, and since [`Self::iter`] skips such entries the
    /// store would silently behave as if it were empty — abandoning every persisted key.
    ///
    /// A database created before the verifier existed has no verifier record; the first open
    /// writes one and adopts the password in use at that point.
    ///
    /// Any missing parent directories of `path` are created.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use hopr_strategy::pix::recovery_store::{PixRecoveryStore, PixRecoveryStoreError};
    ///
    /// # fn main() -> anyhow::Result<()> {
    /// let path = "/var/lib/hoprd/pix_recovery.db";
    /// let store = PixRecoveryStore::open(path, "correct horse battery")?;
    ///
    /// // A mistyped or rotated password is rejected here rather than yielding a store that
    /// // merely looks empty — every persisted key would otherwise be silently abandoned.
    /// assert!(matches!(
    ///     PixRecoveryStore::open(path, "wrong password"),
    ///     Err(PixRecoveryStoreError::WrongPassword)
    /// ));
    /// # let _ = store;
    /// # Ok(())
    /// # }
    /// ```
    pub fn open(path: impl AsRef<Path>, password: &str) -> Result<Self, PixRecoveryStoreError> {
        if let Some(parent) = path.as_ref().parent() {
            std::fs::create_dir_all(parent)?;
        }
        let db = Database::create(path.as_ref())?;

        // Initialize or read the per-database scrypt salt, and ensure the key table exists.
        let salt: [u8; 16] = {
            let write_tx = db.begin_write()?;
            let mut salt_table = write_tx.open_table(PIX_KDF_SALT_TABLE)?;
            // Eagerly copy out the guard value so the AccessGuard drops before insert.
            let existing_salt: Option<[u8; 16]> = salt_table.get(&0u8)?.map(|g| g.value());
            let s = match existing_salt {
                Some(s) => s,
                None => {
                    let buf = random_bytes::<16>();
                    salt_table.insert(&0, buf)?;
                    buf
                }
            };
            drop(salt_table);
            write_tx.open_table(PIX_RECOVERED_KEYS)?;
            write_tx.commit()?;
            s
        };

        let encryption_key = derive_key(password, &salt);

        // Check the derived key against a stored, encrypted constant.
        {
            let write_tx = db.begin_write()?;
            {
                let mut verifier_table = write_tx.open_table(PIX_KDF_VERIFIER_TABLE)?;
                let existing: Option<[u8; VALUE_SIZE]> = verifier_table.get(&0u8)?.map(|g| g.value());
                match existing {
                    Some(stored) => {
                        let plaintext = decrypt(&encryption_key, &VERIFIER_AAD, &stored)
                            .map_err(|_| PixRecoveryStoreError::WrongPassword)?;
                        if plaintext != VERIFIER_PLAINTEXT {
                            return Err(PixRecoveryStoreError::WrongPassword);
                        }
                    }
                    None => {
                        let verifier = encrypt(&encryption_key, &VERIFIER_AAD, &VERIFIER_PLAINTEXT)?;
                        verifier_table.insert(&0u8, verifier)?;
                    }
                }
            }
            write_tx.commit()?;
        }

        Ok(Self {
            db: Arc::new(db),
            encryption_key,
        })
    }

    /// Check whether a key has already been persisted.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use hopr_api::node::PixAddressId;
    /// use hopr_strategy::pix::recovery_store::PixRecoveryStore;
    ///
    /// # fn main() -> anyhow::Result<()> {
    /// # let store: PixRecoveryStore = unimplemented!();
    /// # let id: PixAddressId = unimplemented!();
    /// // Cheaper than `iter()` when only the presence of one entry matters: this reads a single
    /// // row and decrypts nothing.
    /// if !store.contains(&id)? {
    ///     // ... nothing persisted for this deposit yet ...
    /// }
    /// # Ok(())
    /// # }
    /// ```
    pub fn contains(&self, id: &PixAddressId) -> Result<bool, PixRecoveryStoreError> {
        let key = encode_key(id);
        let read_tx = self.db.begin_read()?;
        let table = read_tx.open_table(PIX_RECOVERED_KEYS)?;

        Ok(table.get(key)?.is_some())
    }

    /// Insert an encrypted recovered key.  Returns `true` if the entry was newly
    /// inserted, `false` if the key was already present.
    ///
    /// An existing entry is never overwritten, so its ciphertext and nonce stay as they were.
    /// The check happens inside the write transaction: doing it in a separate read transaction
    /// would double the I/O and leave a window in which another writer could insert the same
    /// key in between.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use hopr_api::{chain::PixDepositSecret, node::PixAddressId};
    /// use hopr_strategy::pix::recovery_store::PixRecoveryStore;
    ///
    /// # fn main() -> anyhow::Result<()> {
    /// # let store: PixRecoveryStore = unimplemented!();
    /// # let id: PixAddressId = unimplemented!();
    /// # let secret: PixDepositSecret = unimplemented!();
    /// assert!(store.insert(&id, &secret)?);
    ///
    /// // The same event replayed is not an error and does not disturb the stored ciphertext —
    /// // the `false` is how a duplicate sweep is recognised.
    /// assert!(!store.insert(&id, &secret)?);
    /// # Ok(())
    /// # }
    /// ```
    pub fn insert(&self, id: &PixAddressId, secret: &PixDepositSecret) -> Result<bool, PixRecoveryStoreError> {
        let key = encode_key(id);
        let write_tx = self.db.begin_write()?;
        let was_inserted = {
            let mut table = write_tx.open_table(PIX_RECOVERED_KEYS)?;
            if table.get(key)?.is_some() {
                false
            } else {
                let plaintext: [u8; 32] = secret.0.as_ref().try_into().expect("PixDepositSecret is 32 bytes");
                let stored = encrypt(&self.encryption_key, &key, &plaintext)?;
                table.insert(key, stored)?;
                true
            }
        };
        write_tx.commit()?;

        Ok(was_inserted)
    }

    /// Remove an entry from the store. Returns whether an entry was actually removed.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use hopr_api::node::PixAddressId;
    /// use hopr_strategy::pix::recovery_store::PixRecoveryStore;
    ///
    /// # fn main() -> anyhow::Result<()> {
    /// # let store: PixRecoveryStore = unimplemented!();
    /// # let id: PixAddressId = unimplemented!();
    /// // Call this only after the sweep has succeeded: dropping the entry earlier discards the
    /// // only means of moving those funds.
    /// let was_present = store.remove(&id)?;
    ///
    /// // Removing an absent entry is a no-op, so a replayed cleanup is harmless.
    /// assert!(!store.remove(&id)?);
    /// # let _ = was_present;
    /// # Ok(())
    /// # }
    /// ```
    pub fn remove(&self, id: &PixAddressId) -> Result<bool, PixRecoveryStoreError> {
        let key = encode_key(id);
        let write_tx = self.db.begin_write()?;
        let was_removed = {
            let mut table = write_tx.open_table(PIX_RECOVERED_KEYS)?;
            table.remove(key)?.is_some()
        };
        write_tx.commit()?;
        Ok(was_removed)
    }

    /// Iterate all stored `(id, secret)` pairs, decrypting each entry.
    ///
    /// On startup the caller uses this to re-submit withdrawals for keys that were
    /// recovered but not yet swept.
    ///
    /// Entries with unreadable rows, corrupt keys or decryption failures are skipped so a
    /// single bad entry does not block recovery for the rest. Every skip is logged, and a
    /// summary is emitted when any entry was dropped: each one is a deposit that will not be
    /// swept, so it must not pass unnoticed.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use hopr_strategy::pix::recovery_store::PixRecoveryStore;
    ///
    /// # fn main() -> anyhow::Result<()> {
    /// let store = PixRecoveryStore::open("/var/lib/hoprd/pix_recovery.db", "correct horse battery")?;
    ///
    /// // Everything still here on startup is a sweep that never completed. Note this decrypts
    /// // every entry eagerly into a `Vec`, so it is a startup-replay call, not a hot path.
    /// for (id, secret) in store.iter()? {
    ///     // ... re-submit the withdrawal, then `store.remove(&id)` once funds have moved ...
    ///     let _ = (id, secret);
    /// }
    /// # Ok(())
    /// # }
    /// ```
    pub fn iter(&self) -> Result<Vec<(PixAddressId, PixDepositSecret)>, PixRecoveryStoreError> {
        let read_tx = self.db.begin_read()?;
        let table = read_tx.open_table(PIX_RECOVERED_KEYS)?;
        let mut results = Vec::new();
        let mut skipped = 0usize;
        for result in table.iter()? {
            let (key_bytes, value_bytes) = match result {
                Ok(kv) => kv,
                Err(error) => {
                    tracing::error!(%error, "unreadable recovery store row, skipping");
                    skipped += 1;
                    continue;
                }
            };
            // Kept as raw bytes: they are the AAD the entry was encrypted under, so the value
            // must be authenticated against what is actually stored, not against a re-encoding.
            let key: [u8; KEY_SIZE] = key_bytes.value();
            let id = match decode_key(&key) {
                Ok(id) => id,
                Err(error) => {
                    tracing::error!(%error, "corrupt recovery store key, skipping entry");
                    skipped += 1;
                    continue;
                }
            };
            // The table is typed `[u8; VALUE_SIZE]`, so the length is already guaranteed.
            let stored: [u8; VALUE_SIZE] = value_bytes.value();
            let plaintext = match decrypt(&self.encryption_key, &key, &stored) {
                Ok(p) => p,
                Err(_) => {
                    tracing::error!(?id, "failed to decrypt recovery store entry, skipping");
                    skipped += 1;
                    continue;
                }
            };
            let secret = PixDepositSecret(plaintext.into());
            results.push((id, secret));
        }
        if skipped > 0 {
            tracing::error!(
                skipped,
                recovered = results.len(),
                "recovery store entries were dropped, their deposits will not be swept"
            );
        }
        Ok(results)
    }
}

#[cfg(test)]
mod tests {
    use hopr_api::types::crypto_random::Randomizable;

    use super::{
        HoprPseudonym, NonZeroU32, PIX_RECOVERED_KEYS, PixAddressId, PixDepositSecret, PixRecoveryStore,
        PixRecoveryStoreError, ReadableDatabase, VALUE_SIZE, encode_key,
    };

    const TEST_PASSWORD: &str = "test-password-for-unit-tests";
    const ALT_PASSWORD: &str = "password-a";

    fn make_id(index: u32) -> PixAddressId {
        (HoprPseudonym::random(), NonZeroU32::new(index).unwrap())
    }

    fn make_secret(byte: u8) -> PixDepositSecret {
        PixDepositSecret([byte; 32].into())
    }

    fn open_temp_store() -> (PixRecoveryStore, tempfile::TempDir) {
        let dir = tempfile::tempdir().unwrap();
        let store = PixRecoveryStore::open(dir.path().join("pix_recovery.db"), TEST_PASSWORD).unwrap();
        (store, dir)
    }

    #[test]
    fn test_open_creates_database_file() {
        let (_store, dir) = open_temp_store();
        assert!(dir.path().join("pix_recovery.db").exists());
    }

    #[test]
    fn test_open_with_missing_parent_creates_directories() {
        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("a").join("b").join("pix.db");
        let store = PixRecoveryStore::open(&nested, TEST_PASSWORD).unwrap();
        assert!(nested.exists());
        drop(store); // must not panic when dropped
    }

    #[test]
    fn test_insert_returns_true_for_new_entry() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);
        assert!(store.insert(&id, &secret).unwrap());
    }

    #[test]
    fn test_insert_returns_false_for_duplicate() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);
        assert!(store.insert(&id, &secret).unwrap());
        assert!(!store.insert(&id, &secret).unwrap());
    }

    #[test]
    fn test_contains_empty_store() {
        let (store, _dir) = open_temp_store();
        assert!(!store.contains(&make_id(1)).unwrap());
    }

    #[test]
    fn test_contains_after_insert() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        store.insert(&id, &make_secret(0xbb)).unwrap();
        assert!(store.contains(&id).unwrap());
    }

    #[test]
    fn test_iter_empty() {
        let (store, _dir) = open_temp_store();
        let entries = store.iter().unwrap();
        assert!(entries.is_empty());
    }

    #[test]
    fn test_iter_returns_inserted_entries() {
        let (store, _dir) = open_temp_store();
        let id1 = make_id(1);
        let id2 = make_id(2);
        let sec1 = make_secret(0x11);
        let sec2 = make_secret(0x22);

        assert!(store.insert(&id1, &sec1).unwrap());
        assert!(store.insert(&id2, &sec2).unwrap());

        let entries = store.iter().unwrap();
        assert_eq!(entries.len(), 2);

        assert!(
            entries
                .iter()
                .any(|(id, s)| id == &id1 && s.0.as_ref() == sec1.0.as_ref())
        );
        assert!(
            entries
                .iter()
                .any(|(id, s)| id == &id2 && s.0.as_ref() == sec2.0.as_ref())
        );
    }

    #[test]
    fn test_survives_reopen() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pix.db");

        let id = make_id(7);
        let secret = make_secret(0x77);

        // Write and close.
        {
            let store = PixRecoveryStore::open(&path, TEST_PASSWORD).unwrap();
            store.insert(&id, &secret).unwrap();
        }

        // Re-open with same password and verify.
        let store = PixRecoveryStore::open(&path, TEST_PASSWORD).unwrap();
        assert!(store.contains(&id).unwrap());
        let entries = store.iter().unwrap();
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].0, id);
        assert_eq!(entries[0].1.0.as_ref(), secret.0.as_ref());
    }

    /// A wrong password must be rejected at `open`. Letting it through would leave every
    /// entry undecryptable, and since `iter` skips those the store would look empty and the
    /// caller would abandon every persisted key without any error.
    #[test]
    fn test_reopen_with_wrong_password_fails() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pix.db");

        let id = make_id(7);
        let secret = make_secret(0x77);

        // Write with password A.
        {
            let store = PixRecoveryStore::open(&path, ALT_PASSWORD).unwrap();
            store.insert(&id, &secret).unwrap();
        }

        assert!(matches!(
            PixRecoveryStore::open(&path, "password-b"),
            Err(PixRecoveryStoreError::WrongPassword)
        ));

        // The data is untouched and still readable with the original password.
        let store = PixRecoveryStore::open(&path, ALT_PASSWORD).unwrap();
        assert_eq!(store.iter().unwrap().len(), 1);
    }

    #[test]
    fn test_remove_existing_and_missing_entry() {
        let (store, _dir) = open_temp_store();
        let id = make_id(3);

        assert!(!store.remove(&id).unwrap(), "removing an absent entry returns false");

        store.insert(&id, &make_secret(0x33)).unwrap();
        assert!(store.remove(&id).unwrap(), "removing a present entry returns true");
        assert!(!store.contains(&id).unwrap());
        assert!(store.iter().unwrap().is_empty());
    }

    #[test]
    fn test_key_uniqueness_per_pseudonym_and_index() {
        let (store, _dir) = open_temp_store();
        let pseudo = HoprPseudonym::random();
        let id_a = (pseudo, NonZeroU32::new(1).unwrap());
        let id_b = (pseudo, NonZeroU32::new(2).unwrap());
        let sec_a = make_secret(0xaa);
        let sec_b = make_secret(0xbb);

        assert!(store.insert(&id_a, &sec_a).unwrap());
        assert!(store.insert(&id_b, &sec_b).unwrap());
        assert!(store.contains(&id_a).unwrap());
        assert!(store.contains(&id_b).unwrap());
        assert_eq!(store.iter().unwrap().len(), 2);
    }

    #[test]
    fn test_different_passwords_produce_different_databases() {
        // Two databases opened with different passwords must encrypt the same
        // plaintext into completely different stored values.
        let dir = tempfile::tempdir().unwrap();
        let path_a = dir.path().join("pix_a.db");
        let path_b = dir.path().join("pix_b.db");

        let id = make_id(1);
        let secret = make_secret(0xaa);

        let store_a = PixRecoveryStore::open(&path_a, ALT_PASSWORD).unwrap();
        let store_b = PixRecoveryStore::open(&path_b, "password-b").unwrap();
        store_a.insert(&id, &secret).unwrap();
        store_b.insert(&id, &secret).unwrap();

        let val_a = raw_stored_value(&store_a, &id).expect("entry in db_a");
        let val_b = raw_stored_value(&store_b, &id).expect("entry in db_b");
        assert_ne!(val_a, val_b, "same plaintext under different passwords must differ");
    }

    // ── Encryption-specific tests ──────────────────────────────────────────

    /// Helper: read the raw stored bytes for a given ID without decrypting.
    fn raw_stored_value(store: &PixRecoveryStore, id: &PixAddressId) -> Option<[u8; VALUE_SIZE]> {
        let key = encode_key(id);
        let read_tx = store.db.begin_read().unwrap();
        let table = read_tx.open_table(PIX_RECOVERED_KEYS).unwrap();
        table.get(key).unwrap().map(|g| g.value())
    }

    #[test]
    fn test_encrypted_ciphertext_differs_from_plaintext() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);
        assert!(store.insert(&id, &secret).unwrap());

        let stored = raw_stored_value(&store, &id).expect("should be present");
        assert_ne!(
            stored.as_slice(),
            secret.0.as_ref(),
            "stored value (nonce + ciphertext) must differ from plaintext"
        );
    }

    #[test]
    fn test_same_plaintext_different_id_yields_different_stored_values() {
        let (store, _dir) = open_temp_store();
        let id1 = make_id(1);
        let id2 = make_id(2);
        let secret = make_secret(0xaa);

        assert!(store.insert(&id1, &secret).unwrap());
        assert!(store.insert(&id2, &secret).unwrap());

        let c1 = raw_stored_value(&store, &id1).expect("entry 1");
        let c2 = raw_stored_value(&store, &id2).expect("entry 2");
        assert_ne!(
            c1, c2,
            "same plaintext under different IDs must produce different stored values"
        );
    }

    #[test]
    fn test_tampered_ciphertext_is_skipped() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);
        assert!(store.insert(&id, &secret).unwrap());

        // Read, tamper one byte of the stored value, write back directly.
        let mut corrupted = raw_stored_value(&store, &id).expect("should be present");
        corrupted[0] ^= 0xff; // flip all bits in the first byte (nonce)

        // Write the corrupted value directly via raw redb.
        let key = encode_key(&id);
        let write_tx = store.db.begin_write().unwrap();
        {
            let mut table = write_tx.open_table(PIX_RECOVERED_KEYS).unwrap();
            table.insert(key, corrupted).unwrap();
        }
        write_tx.commit().unwrap();

        // iter() must skip the tampered entry.
        let entries = store.iter().unwrap();
        assert!(entries.is_empty(), "tampered entry must be skipped");
    }

    /// Each ciphertext is bound to its own database key, so swapping two stored values makes
    /// both unreadable. Without that binding the tags would still verify and `iter` would hand
    /// the caller each ID paired with the *other* entry's secret — a sweep signed with a private
    /// key that does not control the deposit address.
    #[test]
    fn test_ciphertext_moved_to_another_key_is_skipped() {
        let (store, _dir) = open_temp_store();
        let id1 = make_id(1);
        let id2 = make_id(2);
        assert!(store.insert(&id1, &make_secret(0x11)).unwrap());
        assert!(store.insert(&id2, &make_secret(0x22)).unwrap());

        let val1 = raw_stored_value(&store, &id1).expect("entry 1");
        let val2 = raw_stored_value(&store, &id2).expect("entry 2");

        // Swap the two stored values, leaving the keys in place.
        let write_tx = store.db.begin_write().unwrap();
        {
            let mut table = write_tx.open_table(PIX_RECOVERED_KEYS).unwrap();
            table.insert(encode_key(&id1), val2).unwrap();
            table.insert(encode_key(&id2), val1).unwrap();
        }
        write_tx.commit().unwrap();

        assert!(
            store.iter().unwrap().is_empty(),
            "a ciphertext filed under another ID must not decrypt"
        );
    }

    #[test]
    fn test_duplicate_insert_preserves_stored_value() {
        // Same key, re-inserted (duplicate returns false) — `insert` must not overwrite, so
        // the stored value and its nonce stay exactly as the first insert left them.
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);

        store.insert(&id, &secret).unwrap();
        let first = raw_stored_value(&store, &id).expect("first insert");

        // Second insert (duplicate — will NOT overwrite, so the stored value stays)
        store.insert(&id, &secret).unwrap();
        let second = raw_stored_value(&store, &id).expect("second insert");

        assert_eq!(
            first, second,
            "duplicate insert must not overwrite; stored value unchanged"
        );
    }
}
