//! Persistent encrypted store for Exit-side [`PixEvent::PrivateKeyRecovered`] events.
//!
//! # Encryption scheme
//!
//! ```text
//! Config password  ──→  scrypt(password, per-db-salt)  ──→  256-bit key
//!                                                                 │
//!                                              ┌──────────────────┤
//!                                              │                  │
//!                 Per-entry random nonce (12) ─┤         ChaCha20Poly1305
//!                                              │                  │
//!                                  Plaintext   │                  │
//!                                  (32 bytes)  ──→  encrypt      │
//!                                                                 │
//!                                  Stored = nonce (12) ||         │
//!                                           ciphertext (48)    ←──┘
//! ```
//!
//! **Key derivation.**  When the store is opened, the config-supplied password
//! is fed through scrypt (RFC 7914) with recommended parameters (log₂_N = 17,
//! r = 8, p = 1).  A **random 16-byte salt** is generated once per database on
//! first open and persisted in a dedicated redb metadata table, so reopening
//! the same database uses the same salt.  This prevents pre-computation attacks
//! across databases.
//!
//! **Password check.**  A fixed known plaintext is encrypted under the derived key
//! and stored alongside the salt on first open.  Every later open decrypts it and
//! refuses to proceed when it does not match, so a rotated or mistyped password
//! is reported instead of yielding a store whose entries all fail to decrypt.
//!
//! **Per-entry nonce.**  Each encrypted entry begins with a fresh random 12-byte
//! nonce generated by `thread_rng`.  Because every entry gets its own random
//! nonce, there is no risk of nonce reuse even when the same `PixAddressId` is
//! re-encrypted after deletion.
//!
//! **Authenticated encryption.**  Each 32-byte private key is encrypted with
//! ChaCha20Poly1305 (RFC 8439).  The 16-byte authentication tag is appended,
//! producing a 48-byte ciphertext.  Combined with the 12-byte nonce, each stored
//! value is 60 bytes.  Any tampering with the stored ciphertext (bit flips,
//! truncation, etc.) is detected on decryption; the corrupt entry is skipped
//! during iteration and the skip is logged.
//!
//! **Key layout.**  The database key is the `PixAddressId` encoded as
//! `HoprPseudonym::SIZE` bytes of pseudonym followed by a 4-byte big-endian SSA
//! index.  The key is deterministic (no randomness), so `contains()` and
//! `insert()` work naturally.
//!
//! ## Threat model
//!
//! This protects against an attacker who obtains read-only access to the
//! database file (e.g. via a filesystem backup, exfiltration, or stolen disk).
//! Without the config password they cannot derive the encryption key, and
//! without the key they cannot decrypt any entry.
//!
//! It does **not** protect against:
//! - An attacker who also has the config (the password comes from the same config file).
//! - An attacker who can execute code as the node process (they can read the derived key from process memory).
//! - An attacker who can read the node's process environment.  The password is passed via an environment variable,
//!   which is readable through `/proc/<pid>/environ` by the same user and by root, is visible to anything that inspects
//!   the process table, and is inherited by every child process the node spawns.  Keeping the password out of the
//!   config file narrows the on-disk exposure; it does not eliminate exposure to a local attacker.
//! - Side-channel or fault-analysis attacks.
//!
//! ## Recovery on restart
//!
//! On node restart every stored entry is iterated and its sweep re-attempted,
//! providing crash recovery.  An entry is removed only once funds have actually
//! moved, so a deposit that has not landed yet stays pending for a later start
//! rather than being dropped.
//!
//! The store is only opened in the Exit role (when
//! [`crate::pix::strategy::PixStrategyConfig::pix_recovery_db_path`] and
//! [`crate::pix::strategy::PixStrategyConfig::pix_recovery_password_env`] are both set).

use std::{path::Path, sync::Arc};

use chacha20poly1305::{ChaCha20Poly1305, Key, KeyInit, Nonce, aead::Aead};
use hopr_api::{chain::PixDepositSecret, node::PixAddressId, types::crypto_random::random_bytes};
use redb::{Database, ReadableDatabase, ReadableTable, TableDefinition};
use scrypt::{Params as ScryptParams, scrypt};

// Key = pseudonym (10 bytes) + ssa_index (4 bytes)
const KEY_SIZE: usize = PixAddressId::SIZE;

// Value = nonce (12 bytes) + ciphertext (32 + 16 tag)
const NONCE_SIZE: usize = 12;
const VALUE_SIZE: usize = NONCE_SIZE + 32 + 16;

const PIX_RECOVERED_KEYS: TableDefinition<[u8; KEY_SIZE], [u8; VALUE_SIZE]> =
    TableDefinition::new("pix_recovered_keys");
const PIX_RECOVERED_KEY_SCHEMES: TableDefinition<[u8; KEY_SIZE], u8> =
    TableDefinition::new("pix_recovered_key_schemes");

/// Per-database scrypt salt, stored in a separate table.
const PIX_KDF_SALT_TABLE: TableDefinition<u8, [u8; 16]> = TableDefinition::new("pix_kdf_salt");

/// Encrypted [`VERIFIER_PLAINTEXT`], used to reject a wrong password at [`PixRecoveryStore::open`].
const PIX_KDF_VERIFIER_TABLE: TableDefinition<u8, [u8; VALUE_SIZE]> = TableDefinition::new("pix_kdf_verifier");

/// Known plaintext encrypted under the derived key so the key can be checked on open.
const VERIFIER_PLAINTEXT: [u8; 32] = *b"hopr-pix-recovery-store-verifier";

/// Persistent encrypted recovery key store backed by `redb`.
#[derive(Clone)]
pub struct PixRecoveryStore {
    db: Arc<Database>,
    encryption_key: [u8; 32],
}

/// Errors from the PIX recovery store.
#[derive(Debug, thiserror::Error)]
pub enum PixRecoveryStoreError {
    #[error("database error: {0}")]
    Database(#[from] redb::Error),
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("encryption error")]
    Encryption,
    #[error("decryption error")]
    Decryption,
    #[error("corrupt key: {0}")]
    CorruptKey(String),
    #[error("the configured password does not match this recovery store")]
    WrongPassword,
}

impl From<redb::DatabaseError> for PixRecoveryStoreError {
    fn from(error: redb::DatabaseError) -> Self {
        Self::Database(error.into())
    }
}

impl From<redb::TransactionError> for PixRecoveryStoreError {
    fn from(error: redb::TransactionError) -> Self {
        Self::Database(error.into())
    }
}

impl From<redb::TableError> for PixRecoveryStoreError {
    fn from(error: redb::TableError) -> Self {
        Self::Database(error.into())
    }
}

impl From<redb::StorageError> for PixRecoveryStoreError {
    fn from(error: redb::StorageError) -> Self {
        Self::Database(error.into())
    }
}

impl From<redb::CommitError> for PixRecoveryStoreError {
    fn from(error: redb::CommitError) -> Self {
        Self::Database(error.into())
    }
}

// ── Key encoding ─────────────────────────────────────────────────────────────
// Key: `HoprPseudonym::SIZE` bytes of pseudonym + 4 bytes big-endian NonZeroU32.
// Every offset is derived from `HoprPseudonym::SIZE` so the layout follows the type.

fn encode_key(id: &PixAddressId) -> [u8; KEY_SIZE] {
    id.to_bytes()
}

fn decode_key(bytes: &[u8; KEY_SIZE]) -> Result<PixAddressId, PixRecoveryStoreError> {
    PixAddressId::try_from(bytes.as_slice()).map_err(|error| PixRecoveryStoreError::CorruptKey(error.to_string()))
}

fn secret_scheme(secret: &PixDepositSecret) -> u8 {
    match secret {
        PixDepositSecret::Eth(_) => 0,
        PixDepositSecret::Bjj(_) => 1,
    }
}

fn derive_key(password: &str, salt: &[u8]) -> [u8; 32] {
    let mut key = [0u8; 32];

    scrypt(password.as_bytes(), salt, &ScryptParams::RECOMMENDED, &mut key)
        .expect("scrypt with 32-byte output must succeed");
    key
}

// ── Encryption helpers ───────────────────────────────────────────────────────

fn encrypt(key: &[u8; 32], plaintext: &[u8; 32]) -> Result<[u8; VALUE_SIZE], PixRecoveryStoreError> {
    let cipher = ChaCha20Poly1305::new(&Key::from(*key));
    let nonce_bytes = random_bytes::<NONCE_SIZE>();
    let nonce = Nonce::from(nonce_bytes);

    let ciphertext = cipher
        .encrypt(&nonce, plaintext.as_ref())
        .map_err(|_| PixRecoveryStoreError::Encryption)?;

    // ChaCha20Poly1305 output = plaintext_len + 16-byte tag = 48 bytes
    let mut out = [0u8; VALUE_SIZE];
    out[..NONCE_SIZE].copy_from_slice(&nonce_bytes);
    out[NONCE_SIZE..].copy_from_slice(&ciphertext);
    Ok(out)
}

fn decrypt(key: &[u8; 32], stored: &[u8; VALUE_SIZE]) -> Result<[u8; 32], PixRecoveryStoreError> {
    let cipher = ChaCha20Poly1305::new(&Key::from(*key));
    let nonce_arr: [u8; NONCE_SIZE] = stored[..NONCE_SIZE]
        .try_into()
        .map_err(|_| PixRecoveryStoreError::Decryption)?;
    let nonce = Nonce::from(nonce_arr);

    let ciphertext = &stored[NONCE_SIZE..];
    let plaintext = cipher
        .decrypt(&nonce, ciphertext)
        .map_err(|_| PixRecoveryStoreError::Decryption)?;

    Ok(plaintext
        .as_slice()
        .try_into()
        .expect("ChaCha20Poly1305 plaintext is 32 bytes"))
}

impl PixRecoveryStore {
    /// Open (or create) the `redb` database at `path` with encryption key derived from `password`.
    ///
    /// Fails with [`PixRecoveryStoreError::WrongPassword`] when `password` does not match the
    /// one the database was created with. Without that check a rotated or mistyped password
    /// would leave every entry undecryptable, and since [`Self::iter`] skips such entries the
    /// store would silently behave as if it were empty — abandoning every persisted key.
    ///
    /// A database created before the verifier existed has no verifier record; the first open
    /// writes one and adopts the password in use at that point.
    pub fn open(path: impl AsRef<Path>, password: &str) -> Result<Self, PixRecoveryStoreError> {
        if let Some(parent) = path.as_ref().parent() {
            std::fs::create_dir_all(parent)?;
        }
        let db = Database::create(path.as_ref())?;

        // Initialize or read the per-database scrypt salt, and ensure the key table exists.
        let salt: [u8; 16] = {
            let write_tx = db.begin_write()?;
            let mut salt_table = write_tx.open_table(PIX_KDF_SALT_TABLE)?;
            // Eagerly copy out the guard value so the AccessGuard drops before insert.
            let existing_salt: Option<[u8; 16]> = salt_table.get(&0u8)?.map(|g| g.value());
            let s = match existing_salt {
                Some(s) => s,
                None => {
                    let buf = random_bytes::<16>();
                    salt_table.insert(&0, buf)?;
                    buf
                }
            };
            drop(salt_table);
            write_tx.open_table(PIX_RECOVERED_KEYS)?;
            write_tx.open_table(PIX_RECOVERED_KEY_SCHEMES)?;
            write_tx.commit()?;
            s
        };

        let encryption_key = derive_key(password, &salt);

        // Check the derived key against a stored, encrypted constant.
        {
            let write_tx = db.begin_write()?;
            {
                let mut verifier_table = write_tx.open_table(PIX_KDF_VERIFIER_TABLE)?;
                let existing: Option<[u8; VALUE_SIZE]> = verifier_table.get(&0u8)?.map(|g| g.value());
                match existing {
                    Some(stored) => {
                        let plaintext =
                            decrypt(&encryption_key, &stored).map_err(|_| PixRecoveryStoreError::WrongPassword)?;
                        if plaintext != VERIFIER_PLAINTEXT {
                            return Err(PixRecoveryStoreError::WrongPassword);
                        }
                    }
                    None => {
                        let verifier = encrypt(&encryption_key, &VERIFIER_PLAINTEXT)?;
                        verifier_table.insert(&0u8, verifier)?;
                    }
                }
            }
            write_tx.commit()?;
        }

        Ok(Self {
            db: Arc::new(db),
            encryption_key,
        })
    }

    /// Check whether a key has already been persisted.
    pub fn contains(&self, id: &PixAddressId) -> Result<bool, PixRecoveryStoreError> {
        let key = encode_key(id);
        let read_tx = self.db.begin_read()?;
        let table = read_tx.open_table(PIX_RECOVERED_KEYS)?;

        Ok(table.get(key)?.is_some())
    }

    /// Insert an encrypted recovered key.  Returns `true` if the entry was newly
    /// inserted, `false` if the key was already present.
    ///
    /// An existing entry is never overwritten, so its ciphertext and nonce stay as they were.
    /// The check happens inside the write transaction: doing it in a separate read transaction
    /// would double the I/O and leave a window in which another writer could insert the same
    /// key in between.
    pub fn insert(&self, id: &PixAddressId, secret: &PixDepositSecret) -> Result<bool, PixRecoveryStoreError> {
        let key = encode_key(id);
        let write_tx = self.db.begin_write()?;
        let was_inserted = {
            let mut table = write_tx.open_table(PIX_RECOVERED_KEYS)?;
            if table.get(key)?.is_some() {
                false
            } else {
                let plaintext: [u8; 32] = secret
                    .secret()
                    .as_ref()
                    .try_into()
                    .expect("PixDepositSecret is 32 bytes");
                let stored = encrypt(&self.encryption_key, &plaintext)?;
                table.insert(key, stored)?;
                let mut schemes = write_tx.open_table(PIX_RECOVERED_KEY_SCHEMES)?;
                schemes.insert(key, secret_scheme(secret))?;
                true
            }
        };
        write_tx.commit()?;

        Ok(was_inserted)
    }

    /// Remove an entry from the store. Returns whether an entry was actually removed.
    pub fn remove(&self, id: &PixAddressId) -> Result<bool, PixRecoveryStoreError> {
        let key = encode_key(id);
        let write_tx = self.db.begin_write()?;
        let was_removed = {
            let mut table = write_tx.open_table(PIX_RECOVERED_KEYS)?;
            let removed = table.remove(key)?.is_some();
            let mut schemes = write_tx.open_table(PIX_RECOVERED_KEY_SCHEMES)?;
            schemes.remove(key)?;
            removed
        };
        write_tx.commit()?;
        Ok(was_removed)
    }

    /// Iterate all stored `(id, secret)` pairs, decrypting each entry.
    ///
    /// On startup the caller uses this to re-submit withdrawals for keys that were
    /// recovered but not yet swept.
    ///
    /// Entries with unreadable rows, corrupt keys or decryption failures are skipped so a
    /// single bad entry does not block recovery for the rest. Every skip is logged, and a
    /// summary is emitted when any entry was dropped: each one is a deposit that will not be
    /// swept, so it must not pass unnoticed.
    pub fn iter(&self) -> Result<Vec<(PixAddressId, PixDepositSecret)>, PixRecoveryStoreError> {
        let read_tx = self.db.begin_read()?;
        let table = read_tx.open_table(PIX_RECOVERED_KEYS)?;
        let schemes = read_tx.open_table(PIX_RECOVERED_KEY_SCHEMES)?;
        let mut results = Vec::new();
        let mut skipped = 0usize;
        for result in table.iter()? {
            let (key_bytes, value_bytes) = match result {
                Ok(kv) => kv,
                Err(error) => {
                    tracing::error!(%error, "unreadable recovery store row, skipping");
                    skipped += 1;
                    continue;
                }
            };
            let id = match decode_key(&key_bytes.value()) {
                Ok(id) => id,
                Err(error) => {
                    tracing::error!(%error, "corrupt recovery store key, skipping entry");
                    skipped += 1;
                    continue;
                }
            };
            // The table is typed `[u8; VALUE_SIZE]`, so the length is already guaranteed.
            let stored: [u8; VALUE_SIZE] = value_bytes.value();
            let plaintext = match decrypt(&self.encryption_key, &stored) {
                Ok(p) => p,
                Err(_) => {
                    tracing::error!(?id, "failed to decrypt recovery store entry, skipping");
                    skipped += 1;
                    continue;
                }
            };
            // Records created before curve tagging were exclusively secp256k1,
            // so a missing scheme entry is a safe legacy-Ethereum migration.
            let secret = match schemes.get(key_bytes.value())?.map(|value| value.value()).unwrap_or(0) {
                0 => PixDepositSecret::Eth(plaintext.into()),
                1 => PixDepositSecret::Bjj(plaintext.into()),
                value => {
                    tracing::error!(?id, value, "invalid PIX recovery key scheme, skipping");
                    skipped += 1;
                    continue;
                }
            };
            results.push((id, secret));
        }
        if skipped > 0 {
            tracing::error!(
                skipped,
                recovered = results.len(),
                "recovery store entries were dropped, their deposits will not be swept"
            );
        }
        Ok(results)
    }
}

#[cfg(test)]
mod tests {
    use std::num::NonZeroU32;

    use hopr_api::types::{crypto_random::Randomizable, internal::prelude::HoprPseudonym};

    use super::{
        PIX_RECOVERED_KEYS, PixAddressId, PixDepositSecret, PixRecoveryStore, PixRecoveryStoreError, ReadableDatabase,
        VALUE_SIZE, encode_key,
    };

    const TEST_PASSWORD: &str = "test-password-for-unit-tests";
    const ALT_PASSWORD: &str = "password-a";

    fn make_id(index: u32) -> PixAddressId {
        PixAddressId::new(HoprPseudonym::random(), NonZeroU32::new(index).unwrap())
    }

    fn make_secret(byte: u8) -> PixDepositSecret {
        PixDepositSecret::Eth([byte; 32].into())
    }

    fn open_temp_store() -> (PixRecoveryStore, tempfile::TempDir) {
        let dir = tempfile::tempdir().unwrap();
        let store = PixRecoveryStore::open(dir.path().join("pix_recovery.db"), TEST_PASSWORD).unwrap();
        (store, dir)
    }

    #[test]
    fn test_open_creates_database_file() {
        let (_store, dir) = open_temp_store();
        assert!(dir.path().join("pix_recovery.db").exists());
    }

    #[test]
    fn test_open_with_missing_parent_creates_directories() {
        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("a").join("b").join("pix.db");
        let store = PixRecoveryStore::open(&nested, TEST_PASSWORD).unwrap();
        assert!(nested.exists());
        drop(store); // must not panic when dropped
    }

    #[test]
    fn test_insert_returns_true_for_new_entry() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);
        assert!(store.insert(&id, &secret).unwrap());
    }

    #[test]
    fn test_insert_returns_false_for_duplicate() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);
        assert!(store.insert(&id, &secret).unwrap());
        assert!(!store.insert(&id, &secret).unwrap());
    }

    #[test]
    fn test_contains_empty_store() {
        let (store, _dir) = open_temp_store();
        assert!(!store.contains(&make_id(1)).unwrap());
    }

    #[test]
    fn test_contains_after_insert() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        store.insert(&id, &make_secret(0xbb)).unwrap();
        assert!(store.contains(&id).unwrap());
    }

    #[test]
    fn test_iter_empty() {
        let (store, _dir) = open_temp_store();
        let entries = store.iter().unwrap();
        assert!(entries.is_empty());
    }

    #[test]
    fn test_iter_returns_inserted_entries() {
        let (store, _dir) = open_temp_store();
        let id1 = make_id(1);
        let id2 = make_id(2);
        let sec1 = make_secret(0x11);
        let sec2 = make_secret(0x22);

        assert!(store.insert(&id1, &sec1).unwrap());
        assert!(store.insert(&id2, &sec2).unwrap());

        let entries = store.iter().unwrap();
        assert_eq!(entries.len(), 2);

        assert!(
            entries
                .iter()
                .any(|(id, s)| id == &id1 && s.secret().as_ref() == sec1.secret().as_ref())
        );
        assert!(
            entries
                .iter()
                .any(|(id, s)| id == &id2 && s.secret().as_ref() == sec2.secret().as_ref())
        );
    }

    #[test]
    fn test_survives_reopen() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pix.db");

        let id = make_id(7);
        let secret = make_secret(0x77);

        // Write and close.
        {
            let store = PixRecoveryStore::open(&path, TEST_PASSWORD).unwrap();
            store.insert(&id, &secret).unwrap();
        }

        // Re-open with same password and verify.
        let store = PixRecoveryStore::open(&path, TEST_PASSWORD).unwrap();
        assert!(store.contains(&id).unwrap());
        let entries = store.iter().unwrap();
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].0, id);
        assert_eq!(entries[0].1.secret().as_ref(), secret.secret().as_ref());
    }

    /// A wrong password must be rejected at `open`. Letting it through would leave every
    /// entry undecryptable, and since `iter` skips those the store would look empty and the
    /// caller would abandon every persisted key without any error.
    #[test]
    fn test_reopen_with_wrong_password_fails() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pix.db");

        let id = make_id(7);
        let secret = make_secret(0x77);

        // Write with password A.
        {
            let store = PixRecoveryStore::open(&path, ALT_PASSWORD).unwrap();
            store.insert(&id, &secret).unwrap();
        }

        assert!(matches!(
            PixRecoveryStore::open(&path, "password-b"),
            Err(PixRecoveryStoreError::WrongPassword)
        ));

        // The data is untouched and still readable with the original password.
        let store = PixRecoveryStore::open(&path, ALT_PASSWORD).unwrap();
        assert_eq!(store.iter().unwrap().len(), 1);
    }

    #[test]
    fn test_remove_existing_and_missing_entry() {
        let (store, _dir) = open_temp_store();
        let id = make_id(3);

        assert!(!store.remove(&id).unwrap(), "removing an absent entry returns false");

        store.insert(&id, &make_secret(0x33)).unwrap();
        assert!(store.remove(&id).unwrap(), "removing a present entry returns true");
        assert!(!store.contains(&id).unwrap());
        assert!(store.iter().unwrap().is_empty());
    }

    #[test]
    fn test_key_uniqueness_per_pseudonym_and_index() {
        let (store, _dir) = open_temp_store();
        let pseudo = HoprPseudonym::random();
        let id_a = PixAddressId::new(pseudo, NonZeroU32::new(1).unwrap());
        let id_b = PixAddressId::new(pseudo, NonZeroU32::new(2).unwrap());
        let sec_a = make_secret(0xaa);
        let sec_b = make_secret(0xbb);

        assert!(store.insert(&id_a, &sec_a).unwrap());
        assert!(store.insert(&id_b, &sec_b).unwrap());
        assert!(store.contains(&id_a).unwrap());
        assert!(store.contains(&id_b).unwrap());
        assert_eq!(store.iter().unwrap().len(), 2);
    }

    #[test]
    fn test_different_passwords_produce_different_databases() {
        // Two databases opened with different passwords must encrypt the same
        // plaintext into completely different stored values.
        let dir = tempfile::tempdir().unwrap();
        let path_a = dir.path().join("pix_a.db");
        let path_b = dir.path().join("pix_b.db");

        let id = make_id(1);
        let secret = make_secret(0xaa);

        let store_a = PixRecoveryStore::open(&path_a, ALT_PASSWORD).unwrap();
        let store_b = PixRecoveryStore::open(&path_b, "password-b").unwrap();
        store_a.insert(&id, &secret).unwrap();
        store_b.insert(&id, &secret).unwrap();

        let val_a = raw_stored_value(&store_a, &id).expect("entry in db_a");
        let val_b = raw_stored_value(&store_b, &id).expect("entry in db_b");
        assert_ne!(val_a, val_b, "same plaintext under different passwords must differ");
    }

    // ── Encryption-specific tests ──────────────────────────────────────────

    /// Helper: read the raw stored bytes for a given ID without decrypting.
    fn raw_stored_value(store: &PixRecoveryStore, id: &PixAddressId) -> Option<[u8; VALUE_SIZE]> {
        let key = encode_key(id);
        let read_tx = store.db.begin_read().unwrap();
        let table = read_tx.open_table(PIX_RECOVERED_KEYS).unwrap();
        table.get(key).unwrap().map(|g| g.value())
    }

    #[test]
    fn test_encrypted_ciphertext_differs_from_plaintext() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);
        assert!(store.insert(&id, &secret).unwrap());

        let stored = raw_stored_value(&store, &id).expect("should be present");
        assert_ne!(
            stored.as_slice(),
            secret.secret().as_ref(),
            "stored value (nonce + ciphertext) must differ from plaintext"
        );
    }

    #[test]
    fn test_same_plaintext_different_id_yields_different_stored_values() {
        let (store, _dir) = open_temp_store();
        let id1 = make_id(1);
        let id2 = make_id(2);
        let secret = make_secret(0xaa);

        assert!(store.insert(&id1, &secret).unwrap());
        assert!(store.insert(&id2, &secret).unwrap());

        let c1 = raw_stored_value(&store, &id1).expect("entry 1");
        let c2 = raw_stored_value(&store, &id2).expect("entry 2");
        assert_ne!(
            c1, c2,
            "same plaintext under different IDs must produce different stored values"
        );
    }

    #[test]
    fn test_tampered_ciphertext_is_skipped() {
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);
        assert!(store.insert(&id, &secret).unwrap());

        // Read, tamper one byte of the stored value, write back directly.
        let mut corrupted = raw_stored_value(&store, &id).expect("should be present");
        corrupted[0] ^= 0xff; // flip all bits in the first byte (nonce)

        // Write the corrupted value directly via raw redb.
        let key = encode_key(&id);
        let write_tx = store.db.begin_write().unwrap();
        {
            let mut table = write_tx.open_table(PIX_RECOVERED_KEYS).unwrap();
            table.insert(key, corrupted).unwrap();
        }
        write_tx.commit().unwrap();

        // iter() must skip the tampered entry.
        let entries = store.iter().unwrap();
        assert!(entries.is_empty(), "tampered entry must be skipped");
    }

    #[test]
    fn test_duplicate_insert_preserves_stored_value() {
        // Same key, re-inserted (duplicate returns false) — `insert` must not overwrite, so
        // the stored value and its nonce stay exactly as the first insert left them.
        let (store, _dir) = open_temp_store();
        let id = make_id(1);
        let secret = make_secret(0xaa);

        store.insert(&id, &secret).unwrap();
        let first = raw_stored_value(&store, &id).expect("first insert");

        // Second insert (duplicate — will NOT overwrite, so the stored value stays)
        store.insert(&id, &secret).unwrap();
        let second = raw_stored_value(&store, &id).expect("second insert");

        assert_eq!(
            first, second,
            "duplicate insert must not overwrite; stored value unchanged"
        );
    }
}
